/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

const tintColorLight = '#E50914';
const tintColorDark = '#E50914';

const shellLight = {
  background: '#F6F1EA',
  surface: '#FFFCF8',
  surfaceAlt: '#F1E7DB',
  card: '#FFFFFF',
  border: '#E6D8CA',
  mutedText: '#6F6475',
  chipIdle: '#EFE4D7',
  chipActive: '#E50914',
  chipTextIdle: '#51485B',
  chipTextActive: '#FFFFFF',
  overlay: 'rgba(23, 16, 28, 0.42)',
};

const shellDark = {
  background: '#0A0C12',
  surface: '#111522',
  surfaceAlt: '#1B2030',
  card: '#151A27',
  border: '#252B3A',
  mutedText: '#9BA4B8',
  chipIdle: '#20283A',
  chipActive: '#E50914',
  chipTextIdle: '#D7DDEE',
  chipTextActive: '#FFFFFF',
  overlay: 'rgba(5, 7, 14, 0.62)',
};

export const Colors = {
  light: {
    text: '#181421',
    background: shellLight.background,
    tint: tintColorLight,
    icon: '#594D66',
    tabIconDefault: '#786C86',
    tabIconSelected: tintColorLight,
    homeSurface: shellLight.background,
    homeSurfaceAlt: shellLight.surfaceAlt,
    homeCard: shellLight.card,
    homeChipIdle: shellLight.chipIdle,
    homeChipActive: shellLight.chipActive,
    homeChipTextIdle: shellLight.chipTextIdle,
    homeChipTextActive: shellLight.chipTextActive,
    homeOverlay: shellLight.overlay,
    homeMutedText: shellLight.mutedText,
    shellBackground: shellLight.background,
    shellSurface: shellLight.surface,
    shellSurfaceAlt: shellLight.surfaceAlt,
    shellCard: shellLight.card,
    shellBorder: shellLight.border,
    shellMutedText: shellLight.mutedText,
    shellChipIdle: shellLight.chipIdle,
    shellChipActive: shellLight.chipActive,
    shellChipTextIdle: shellLight.chipTextIdle,
    shellChipTextActive: shellLight.chipTextActive,
    shellOverlay: shellLight.overlay,
    shellFabBackground: tintColorLight,
    shellFabForeground: '#FFFFFF',
  },
  dark: {
    text: '#FFFFFF',
    background: shellDark.background,
    tint: tintColorDark,
    icon: '#D7DDEE',
    tabIconDefault: '#B9C1D4',
    tabIconSelected: tintColorDark,
    homeSurface: shellDark.background,
    homeSurfaceAlt: shellDark.surfaceAlt,
    homeCard: shellDark.card,
    homeChipIdle: shellDark.chipIdle,
    homeChipActive: shellDark.chipActive,
    homeChipTextIdle: shellDark.chipTextIdle,
    homeChipTextActive: shellDark.chipTextActive,
    homeOverlay: shellDark.overlay,
    homeMutedText: shellDark.mutedText,
    shellBackground: shellDark.background,
    shellSurface: shellDark.surface,
    shellSurfaceAlt: shellDark.surfaceAlt,
    shellCard: shellDark.card,
    shellBorder: shellDark.border,
    shellMutedText: shellDark.mutedText,
    shellChipIdle: shellDark.chipIdle,
    shellChipActive: shellDark.chipActive,
    shellChipTextIdle: shellDark.chipTextIdle,
    shellChipTextActive: shellDark.chipTextActive,
    shellOverlay: shellDark.overlay,
    shellFabBackground: tintColorDark,
    shellFabForeground: '#FFFFFF',
  },
};
